---
title: "Nathan Kim's CV"
author: Nathan Kim
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
library(lubridate)
library(glue)
source(here::here("content/cv/cv_printing_functions.r"))

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1Q6UT_U3Ox4Y0BZUx0wUuLIs2KTUl_6qHigLjXcvRPgQ/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)
date <- Sys.Date()
date <- glue("{format(date, '%B')} {day(date)}th, {year(date)}")
```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online at [https://nathankim.name/files/cv.html](https://nathankim.name/files/cv.html)")
} else {
  cat("[<i class='fas fa-download'></i> Download as PDF.](https://github.com/18kimn/nathankim/raw/master/static/files/cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R packages [**pagedown**](https://github.com/rstudio/pagedown) and [**datadrivencv**](http://nickstrayer.me/datadrivencv/).

The source code is available [here](https://github.com/18kimn/nathankim/tree/master/content/cv).

Last updated on `r date`.



Main
================================================================================

Nathan Kim {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 

```




Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```

Awards {data-icon=award data-concise=true}
--------------------------------------------------------------------------------
```{r}
CV %<>% print_section('awards')
```

Publications {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
```{r}

CV %<>% print_section('publications')

```


Work Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('industy_experience_aside') -->
<!-- ``` -->
<!-- ::: -->

```{r}
CV %<>% print_section('work_experience')
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

On-Campus Activities {data-icon=users}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('on-campus_activities')
```


<!-- <br> -->
<!-- <br> -->

<!-- ```{r} -->
<!-- CV %<>% print_links() -->
<!-- ``` -->

